package com.secureVerify.model;

public enum SecureVerifyEmailType {

	CANDIDATE_REGISTRATION_EMAIL_TO_CANDIDATE(1), 
	EMPLOYER_REGISTRATION_EMAIL_TO_EMPLOYER(2), 
	CANDIDATE_PASSWORD_RECOVERY(3), 
	EMPLOYER_PASSWORD_RECOVERY(4), 
	ADMIN_PASSWORD_RECOVERY(5), 
	INTERVIEWER_PASSWORD_RECOVERY(6), 
	AGENT_PASSWORD_RECOVERY(7), 
	EMPLOYER_ADD_CANDIDATE_EMAIL_TO_CANDIDATE(8), 
	EMPLOYER_ADD_EXISTING_CANDIDATE_EMAIL_TO_CANDIDATE(9), 
	EMPLOYER_ADD_CANDIDATE_EMAIL_TO_EMPLOYER(10),
	CANDIDATE_SCHEDULED_TIME_SLOT_SELECT_BY_CANDIDATE_EMAIL_TO_CANDIDATE(11), 
	CANDIDATE_SCHEDULED_TIME_SLOT_SELECT_BY_CANDIDATE_EMAIL_TO_EMPLOYER(12), 
	CANDIDATE_SCHEDULED_TIME_SLOT_SELECT_BY_CANDIDATE_EMAIL_TO_INTERVIEWER(13), 
	CANDIDATE_SCHEDULED_TIME_SLOT_SELECT_BY_CANDIDATE_EMAIL_TO_AGENT(14), 
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_CANDIDATE_EMAIL_TO_CANDIDATE(15),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_CANDIDATE_EMAIL_TO_EMPLOYER(16),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_CANDIDATE_EMAIL_TO_INTERVIEWER(17),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_CANDIDATE_EMAIL_TO_AGENT(18), 
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_INTERVIEWER_EMAIL_TO_CANDIDATE(19),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_INTERVIEWER_EMAIL_TO_EMPLOYER(20),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_INTERVIEWER_EMAIL_TO_INTERVIEWER(21),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_INTERVIEWER_EMAIL_TO_AGENT(22), 
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_AGENT_EMAIL_TO_CANDIDATE(23),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_AGENT_EMAIL_TO_EMPLOYER(24),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_AGENT_EMAIL_TO_INTERVIEWER(25),
	CANDIDATE_SCHEDULED_TIME_SLOT_CHANGED_BY_AGENT_EMAIL_TO_AGENT(26),
	INTERVIEWER_CANDIDATE_PICKUP_EMAIL_TO_CANDIDATE(27),
	INTERVIEWER_CANDIDATE_PICKUP_EMAIL_TO_EMPLOYER(28),
	INTERVIEWER_CANDIDATE_PICKUP_EMAIL_TO_INTERVIEWER(29),
	INTERVIEWER_CANDIDATE_PICKUP_EMAIL_TO_AGENT(30),
	INTERVIEWER_CANDIDATE_FEEDBACK_EMAIL_TO_CANDIDATE(31),
	INTERVIEWER_CANDIDATE_FEEDBACK_EMAIL_TO_EMPLOYER(32),
	INTERVIEWER_CANDIDATE_FEEDBACK_EMAIL_TO_INTERVIEWER(33),
	INTERVIEWER_CANDIDATE_FEEDBACK_EMAIL_TO_AGENT(34),
	ADMIN_SAVE_INTERVIEWER_EMAIL_TO_ADMIN(35),
	ADMIN_SAVE_INTERVIEWER_EMAIL_TO_INTERVIEWER(36),
	ADMIN_UPDATE_INTERVIEWER_EMAIL_TO_ADMIN(37),
	ADMIN_UPDATE_INTERVIEWER_EMAIL_TO_INTERVIEWER(38),
	ADMIN_SAVE_AGENT_EMAIL_TO_ADMIN(39),
	ADMIN_SAVE_AGENT_EMAIL_TO_AGENT(40),
	ADMIN_UPDATE_AGENT_EMAIL_TO_ADMIN(41),
	ADMIN_UPDATE_AGENT_EMAIL_TO_AGENT(42);
	
	private int value;
	
	private SecureVerifyEmailType(int value){
		this.value = value;
	}
	
	public int getValue() {
		return this.value;
	}
	
}
